[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/assets/*"
  [headers.values]
    cache-control = '''
    max-age=31536000,
    immutable
    '''

[build]
  publish = "dist/"
  command = "npm run build"


[context.develop]
  command = "npm run build:staging"

[context.deploy-preview]
  command = "npm run build:staging"
