[[headers]]
  for = "/manifest.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"

[[headers]]
  for = "/assets/*"
  [headers.values]
    cache-control = '''
    max-age=31536000,
    immutable
    '''

[build]
  base = "templates/chouquette"
  publish = "dist/"
  command = "cd ../../ && npm ci &&  npm run transform:chouquette && npm run build && mv dist templates/chouquette/dist"


[context.develop]
  command = "cd ../../ && npm ci && npm run transform:chouquette &&  npm run build:staging && mv dist templates/chouquette/dist"

[context.deploy-preview]
  command = "cd ../../ && npm ci && npm run transform:chouquette && npm run build:staging && mv dist templates/chouquette/dist"
