name: Deploy to Staging

on:
  push:
    branches:
      - develop
    paths:
      - 'supabase/**'
  workflow_dispatch:


jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }}
      SUPABASE_DB_PASSWORD: ${{ secrets.STAGING_DB_PASSWORD }}
      STAGING_PROJECT_ID: ${{ secrets.STAGING_PROJECT_ID }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        id: cache
        with:
          path: ~/.npm          
          key: node-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - run: |
          npm run supabase -- link --project-ref $STAGING_PROJECT_ID
          npm run supabase -- db push
          npm run supabase -- functions deploy end-bet